source("helpers/descriptive_statistics_helper.R")

# load the prepared dataset
waiting_lists <- read_csv("data_prep/quarterly_totals_per_speciality.csv")
str(waiting_lists)
# set time bands to be an ordered factor
waiting_lists$Time_Bands <- factor(waiting_lists$Time_Bands, 
                                   ordered = TRUE, 
                                   levels = c("<1Yr", ">1Yr"))
# specialities should also be a factor (unordered)
waiting_lists$Speciality_Name <- as.factor(waiting_lists$Speciality_Name)
str(waiting_lists)

######################################
# Repeated Measures ANOVA
######################################
# https://www.datanovia.com/en/lessons/repeated-measures-anova-in-r/

# get numeric variables
numeric_variables <- sapply(waiting_lists, is.numeric)
numeric_variables

# create numeric only subset of data
numeric_data <- waiting_lists[numeric_variables]
colnames(numeric_data)

# create summary of numeric data
numeric_summary <- do.call(cbind, lapply(numeric_data, summary))

#########################################
# check for outliers
boxplot(numeric_data)

class(numeric_data)
identify_outliers(numeric_data, variable = `2014.1`)

Q <- quantile(waiting_lists$`2014.1`, probs=c(.25, .75), na.rm = FALSE)






#####################################################################
# Use double-tab for structure of sapply()
numeric_variables <- sapply(waiting_lists, is.numeric)
numeric_variables

# We can use this logic to create a subset of the data
numerical_data <- waiting_lists[numeric_variables]
colnames(numerical_data)

# We can use the lapply() function to return a named list
# where each list member has a corresponding name
lapply(numerical_data, summary)

?cbind()
# cbind() combines objects by rows and columns
# so we can use this function to create a dataset
# of the lapply() output

# do.call() function will allow us to 
# apply the cbind() to each element generated by lapply()
?do.call
# do.call(what, args, quote = FALSE, envir = parent.frame())
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))

# Error message shows additional ine - caused by NA's
# We could drop NA's but that will only fix this one issue
# Instead we need to go back to the source and drop the NA's

file_data <- file_data[complete.cases(file_data),]
numerical_data <- file_data[numeric_variable_list]
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))
numerical_summary

# We can do a swap with summary values as columns and variables as rows 
# then we use rbind()
alt_numerical_summary <-  do.call(rbind, lapply(numerical_data, summary))
alt_numerical_summary


