source("helpers/descriptive_statistics_helper.R")

# load the prepared dataset
waiting_lists <- read_csv("data_prep/modified_waiting_list_data.csv")
# and the speciality and hospital group lookups
specialities <- read_csv("data_prep/speciality_lookup.csv")
hospital_groups <- read_csv("data_prep/hospital_group_lookup.csv")


# due to the large number of independent variables (77 specialities)
# a principal component analysis will be performed to reduce dimensions 


#####################################################################
# Use double-tab for structure of sapply()
numeric_variables <- sapply(waiting_lists, is.numeric)
numeric_variables

# We can use this logic to create a subset of the data
numerical_data <- waiting_lists[numeric_variables]
colnames(numerical_data)

# We can use the lapply() function to return a named list
# where each list member has a corresponding name
lapply(numerical_data, summary)

?cbind()
# cbind() combines objects by rows and columns
# so we can use this function to create a dataset
# of the lapply() output

# do.call() function will allow us to 
# apply the cbind() to each element generated by lapply()
?do.call
# do.call(what, args, quote = FALSE, envir = parent.frame())
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))

# Error message shows additional ine - caused by NA's
# We could drop NA's but that will only fix this one issue
# Instead we need to go back to the source and drop the NA's

file_data <- file_data[complete.cases(file_data),]
numerical_data <- file_data[numeric_variable_list]
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))
numerical_summary

# We can do a swap with summary values as columns and variables as rows 
# then we use rbind()
alt_numerical_summary <-  do.call(rbind, lapply(numerical_data, summary))
alt_numerical_summary



# Interactions with correlations
# using the corrplot() function
# Create a mtrix of high correlations
opar <- par(no.readonly = TRUE)
library(corrplot)
# tl.col = text colour
# tl.cex = text size
corrplot(corr = cor(numerical_data), tl.col = "Black", tl.cex = 0.9)
